retrieve old version from leo resources, new version from /charts

diff --git a/.github/workflows/make_leo_pr.yml b/.github/workflows/make_leo_pr.yml
--- a/.github/workflows/make_leo_pr.yml
+++ b/.github/workflows/make_leo_pr.yml
@@ -13,27 +13,17 @@ jobs:
         with:
           token: ${{ secrets.BROADBOT_TOKEN }} # Has to be set at checkout AND later when pushing to work
 
-      - name: Find out next chart version from cromwhelm repository
+      - name: Find out latest chart version from cromwhelm repository
         run: |
-          currentVersionGCP=$(grep '^version:' cromwell-helm/Chart.yaml | awk '{print $NF}')
-          currentVersionCOA=$(grep '^version:' coa-helm/Chart.yaml | awk '{print $NF}')
+          function getLatestChartVersion(){
+            ls $1 | \
+            grep ^cromwell- | \
+            sed 's:cromwell-::; s:.tgz::' | \
+            sort -V | \
+            tail -1
+          }
 
-          # this will increment only the patch version digit. For example, it will update 0.1.10 => 0.1.11
-          nextVersionGCP=$(echo ${currentVersionGCP} | awk -F. -v OFS=. '{$NF += 1 ; print}')
-          nextVersionCOA=$(echo ${currentVersionGCP} | awk -F. -v OFS=. '{$NF += 1 ; print}')
-
-          if [ $currentVersionCOA != $currentVersionGCP ]; then
-            echo "COA and GCP current versions are not equal; this should not happen. Exiting"
-            exit 1
-          fi
-
-          if [ $nextVersionCOA != $nextVersionGCP ]; then
-            echo "COA and GCP next versions are not equal; this should not happen. Exiting"
-            exit 1
-          fi
-
-          echo "OLD_CROMWELL_HELM_V=$currentVersionGCP" >> $GITHUB_ENV
-          echo "NEW_CROMWELL_HELM_V=$nextVersionGCP" >> $GITHUB_ENV
+          echo "NEW_CROMWELL_HELM_V=$(getLatestChartVersion charts)" >> $GITHUB_ENV
 
       - name: Clone leonardo
         uses: actions/checkout@v2
@@ -46,10 +36,35 @@ jobs:
         env:
           BROADBOT_TOKEN: ${{ secrets.BROADBOT_TOKEN }}
         run: |
+          function getVersionFromReference(){
+            cat $1 | \
+            sed -e '/cromwellApp/,/chartVersion/!d' -e 's:^[ ]*::' | \
+            tail -1 | \
+            awk -F'"' '{print $2}'
+          }
+
+          function getVersionFromDocker(){
+            grep "ENV CROMWELL_CHART_VERSION" $1 | awk -F'[ ]' '{ print $3 }'
+          }
+
           cd leonardo
-          NEW_BRANCH_NAME="cromwell_helm_${NEW_CROMWELL_HELM_V}"
+
+          versionFromReference=$(getVersionFromReference http/src/main/resources/reference.conf)
+          versionFromDocker=$(getVersionFromDocker Dockerfile)
+
+          if [ $versionFromReference != $versionFromDocker ]; then
+            echo "ERROR: Cromwell versions in reference.conf and Dockerfile do not match." \
+                 "($versionFromReference != $versionFromDocker)" \
+            exit 1
+          fi
+
+          echo "OLD_CROMWELL_HELM_V=$versionFromReference" >> $GITHUB_ENV
+
+
+          NEW_BRANCH_NAME="cromwell_helm_${NEW_CROMWELL_HELM_V}-AUTOMERGE"
           TEMP=$(mktemp)
           git checkout -b "${NEW_BRANCH_NAME}"
+
           SED_STRING="s/${OLD_CROMWELL_HELM_V}/${NEW_CROMWELL_HELM_V}/g"
           FILES=( "Dockerfile" "http/src/main/resources/reference.conf" )
           for i in "${FILES[@]}"
@@ -59,10 +74,11 @@ jobs:
             mv ${TEMP} ${i}
             git add ${i}
           done
+
           echo "Pushing to leonardo branch ${NEW_BRANCH_NAME}"
           git config --global user.name "broadbot"
           git config --global user.email "broadbot@broadinstitute.org"
-          git commit -m "Updating Cromwell version to ${NEW_CROMWELL_HELM_V}"
+          git commit -m "Auto-update Cromwell version to ${NEW_CROMWELL_HELM_V}"
           git push https://broadbot:$BROADBOT_TOKEN@github.com/broadinstitute/leonardo.git ${NEW_BRANCH_NAME}
           echo ::set-output name=NEW_BRANCH_NAME::${NEW_BRANCH_NAME}
       - name: Create leonardo PR
